# Generated by Django 5.2.2 on 2025-06-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_venta', '0002_alter_pedido_usuario_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='preparado',
            field=models.BooleanField(default=False),
        ),
    ]
