# Generated by Django 5.2.2 on 2025-06-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_venta', '0004_pedido_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
