# Generated by Django 5.2.2 on 2025-06-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usuario', '0002_usuario_groups_usuario_is_staff_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
